name: starter_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  
  
  cupertino_icons: ^1.0.2
  retrofit: ^4.0.1
  logger: ^2.0.1
  json_annotation: ^4.8.1
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.2

flutter:  
  uses-material-design: true
  